const box1 = document.getElementById("box1")
const box2 = document.getElementById("box2")
const box3 = document.getElementById("box3")
const box4 = document.getElementById("box4")
const box5 = document.getElementById("box5")
const box6 = document.getElementById("box6")
const box7 = document.getElementById("box7")
const box8 = document.getElementById("box8")

box1.addEventListener("click", function () {
  box1.classList.toggle("clicked")
  box2.classList.remove("clicked")
  box3.classList.remove("clicked")
  box4.classList.remove("clicked")
  box5.classList.remove("clicked")
  box6.classList.remove("clicked")
  box7.classList.remove("clicked")
  box8.classList.remove("clicked")
})

box2.addEventListener("click", function () {
  box1.classList.remove("clicked")
  box2.classList.toggle("clicked")
  box3.classList.remove("clicked")
  box4.classList.remove("clicked")
  box5.classList.remove("clicked")
  box6.classList.remove("clicked")
  box7.classList.remove("clicked")
  box8.classList.remove("clicked")
})
box3.addEventListener("click", function () {
  box1.classList.remove("clicked")
  box2.classList.remove("clicked")
  box3.classList.toggle("clicked")
  box4.classList.remove("clicked")
  box5.classList.remove("clicked")
  box6.classList.remove("clicked")
  box7.classList.remove("clicked")
  box8.classList.remove("clicked")
})
box4.addEventListener("click", function () {
  box1.classList.remove("clicked")
  box2.classList.remove("clicked")
  box3.classList.remove("clicked")
  box4.classList.toggle("clicked")
  box5.classList.remove("clicked")
  box6.classList.remove("clicked")
  box7.classList.remove("clicked")
  box8.classList.remove("clicked")
})
box5.addEventListener("click", function () {
  box1.classList.remove("clicked")
  box2.classList.remove("clicked")
  box3.classList.remove("clicked")
  box4.classList.remove("clicked")
  box5.classList.toggle("clicked")
  box6.classList.remove("clicked")
  box7.classList.remove("clicked")
  box8.classList.remove("clicked")
})
box6.addEventListener("click", function () {
  box1.classList.remove("clicked")
  box2.classList.remove("clicked")
  box3.classList.remove("clicked")
  box4.classList.remove("clicked")
  box5.classList.remove("clicked")
  box6.classList.toggle("clicked")
  box7.classList.remove("clicked")
  box8.classList.remove("clicked")
})
box7.addEventListener("click", function () {
  box1.classList.remove("clicked")
  box2.classList.remove("clicked")
  box3.classList.remove("clicked")
  box4.classList.remove("clicked")
  box5.classList.remove("clicked")
  box6.classList.remove("clicked")
  box7.classList.toggle("clicked")
  box8.classList.remove("clicked")
})
box8.addEventListener("click", function () {
  box1.classList.remove("clicked")
  box2.classList.remove("clicked")
  box3.classList.remove("clicked")
  box4.classList.remove("clicked")
  box5.classList.remove("clicked")
  box6.classList.remove("clicked")
  box7.classList.remove("clicked")
  box8.classList.toggle("clicked")
})
const box9 = document.getElementById("box11")
const box10 = document.getElementById("box22")

box9.addEventListener("click", function () {
  box9.classList.toggle("clicked2")
  box10.classList.remove("clicked2")
})
box10.addEventListener("click", function () {
  box9.classList.remove("clicked2")
  box10.classList.toggle("clicked2")
})